/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "primary-dark": "var(--color-primary-dark)",
        "primary-contrast": "var(--color-primary-contrast)",
        secondary: "var(--color-secondary)",
        "secondary-contrast": "var(--color-secondary-contrast)",
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        "surface-alt": "var(--color-surface-alt)",
        text: "var(--color-text)",
        muted: "var(--color-muted)",
        border: "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        error: "var(--color-error)",
        "error-bg": "var(--color-error-bg)",
        "error-border": "var(--color-error-border)",
        success: "var(--color-success)",
        "success-bg": "var(--color-success-bg)",
        "success-border": "var(--color-success-border)",
        warning: "var(--color-warning)",
        "warning-bg": "var(--color-warning-bg)",
      },
      fontFamily: {
        base: ["Cairo", "Tajawal", "Segoe UI", "Tahoma", "Arial", "sans-serif"],
      },
      fontSize: {
        display: ["28px", { lineHeight: "1.3", fontWeight: "800" }],
        h1: ["22px", { lineHeight: "1.35", fontWeight: "700" }],
        h2: ["18px", { lineHeight: "1.4", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        body: ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        label: ["14px", { lineHeight: "1.3", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        overline: ["11px", { lineHeight: "1.3", fontWeight: "700", letterSpacing: "0.02em" }],
      },
      spacing: {
        0: "0",
        px: "1px",
        "space-0": "4px",
        "space-1": "8px",
        "space-1-5": "12px",
        "space-2": "16px",
        "space-2-5": "20px",
        "space-3": "24px",
        "space-4": "40px",
        "space-5": "64px",
        touch: "44px",
        nav: "64px",
      },
      borderRadius: {
        sm: "8px",
        DEFAULT: "12px",
        lg: "18px",
        full: "999px",
      },
      minHeight: {
        touch: "44px",
      },
      minWidth: {
        touch: "44px",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        "nav-up": "var(--shadow-nav-up)",
      },
      transitionDuration: {
        fast: "120ms",
        base: "200ms",
        slow: "320ms",
        celebrate: "480ms",
      },
      transitionTimingFunction: {
        standard: "cubic-bezier(0.2, 0, 0, 1)",
        decel: "cubic-bezier(0, 0, 0, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [],
};
